# CrewAI agent configuration – Crossnection MVP (Data, Stats, Explain)
# Compatible with modern crewai YAML (no root "agents:" block)

# ─────────────────────────────────────────────────────────────────────────────
# DATA AGENT – integrates & cleans user‑provided driver datasets
# ─────────────────────────────────────────────────────────────────────────────

data_agent:
  class_path: crossnection_mvp.agents.data_agent.DataAgent  # thin subclass adds join‑key discovery
  role: Data Integration & Validation
  goal: |
    Ingest user‑uploaded CSV driver datasets, profile & validate their schema,
    discover (or synthesise) a unique join‑key, and output a single cleaned,
    normalised table ready for statistical analysis.
    When using the cross_data_profiler tool, always specify "csv_folder" with the actual folder path,
    such as "examples/driver_csvs", and specify "kpi" and "mode" parameters.
  llm:
    model: gpt-4o-mini
    temperature: 0.0
  tools:
    - cross_data_profiler
  memory:
    strategy: vectorstore
    ttl: 7776000   # 90 days expressed in seconds

# ─────────────────────────────────────────────────────────────────────────────
# STATS AGENT – computes correlations & ranking
# ─────────────────────────────────────────────────────────────────────────────

stats_agent:
  class_path: crossnection_mvp.agents.stats_agent.StatsAgent
  role: Statistical Insight Generator
  goal: |
    Perform multivariate statistical analysis on the unified dataset to
    correlate each driver with the target KPI, rank their impact, and detect
    outliers and spurious relationships.
  llm:
    model: gpt-4o-mini
    temperature: 0.0
  tools:
    - cross_stat_engine
  memory:
    strategy: episodic
    ttl: 7776000

# ─────────────────────────────────────────────────────────────────────────────
# EXPLAIN AGENT – crafts human‑validated narratives
# ─────────────────────────────────────────────────────────────────────────────

explain_agent:
  class_path: crossnection_mvp.agents.explain_agent.ExplainAgent
  role: Insight Narrator & Validator
  goal: |
    Trasformare i risultati statistici in narrative comprensibili di root-cause, presentare
    una bozza all'utente per validazione (human-in-the-loop), e integrare il feedback
    dell'utente per produrre un report finale che sia AZIONABILE.
    
    Per ogni correlazione significativa (p < 0.05):
    1. Crea una sezione che spiega il potenziale impatto in linguaggio business
    2. Fornisci una visualizzazione mentale chiara di come il driver influenza il KPI
    3. Traduci la forza della correlazione in termini di priorità operativa
    
    Nel draft, termina ogni insight con un punto interrogativo esplicito per
    invitare l'utente a confermare o modificare l'interpretazione proposta.
    
    Nel report finale, incorpora le correzioni utente e organizza gli insight
    in sezioni "Azione Immediata", "Monitoraggio Consigliato" e "Ipotesi da Verificare".
  llm:
    model: gpt-4o-mini
    temperature: 0.1
  tools:
    - cross_insight_formatter
  memory:
    strategy: chat
    ttl: 2592000   # 30 days in seconds